name: monitorlibrary
description: Monitor Platform Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.0
  firebase_messaging: ^10.0.6
  firebase_core: ^1.6.0
#  cloud_firestore: ^0.14.4
  firebase_storage: ^10.0.3
  permission_handler: ^8.1.4+2
  unicorndial: ^1.1.5
  shared_preferences: ^2.0.7
  path_provider: ^2.0.3
#  sensors: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  flutter_google_places: ^0.3.0
  intl: ^0.17.0
  http: ^0.13.3
  google_maps_flutter: ^2.0.8
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^1.7.3
  mobmongo: ^0.0.14
  grouped_buttons: ^1.0.4
  path: ^1.8.0
  cached_network_image: ^3.1.0
  flutter_dotenv: ^5.0.2
  page_transition: ^2.0.2
  responsive_builder: ^0.4.1
  google_fonts: ^2.1.0
  geolocator: ^7.6.0
  image: ^3.0.2
  intent: ^1.4.0
#  extended_image: ^3.0.0
  video_thumbnail: ^0.4.3
  android_intent: ^2.0.2
  flutter_credit_card: ^2.0.0
  introduction_screen: ^2.1.0
  uuid: ^3.0.4
  geocoding:
  chewie: ^1.2.2
  video_player: ^2.1.15
  maps_toolkit: ^2.0.0
  focused_menu: ^1.0.5
  universal_platform: ^1.0.0+1
#  flutter_local_notifications:
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  image_size_getter: ^1.0.0
  get:
  crypto:
  hive: ^2.0.4
  connectivity: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

