name: monitorlibrary
description: Monitor Platform Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_core: ^1.0.1
#  cloud_firestore: ^0.14.4
  firebase_storage: ^8.0.0
  permission_handler: ^6.1.0
  unicorndial: ^1.1.5
  shared_preferences: ^2.0.4
  path_provider: ^2.0.1
  sensors: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  flutter_google_places: ^0.2.8
  intl: ^0.17.0
  http: ^0.13.0
  google_maps_flutter: ^2.0.1
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^1.7.3
#  mobmongo: ^0.0.8+1
  grouped_buttons: ^1.0.4
  path: ^1.8.0
  cached_network_image: ^2.5.1
  flutter_dotenv: ^3.1.0
  page_transition: ^1.1.7+6
  responsive_builder:
  google_fonts: ^2.0.0
  geolocator: ^7.0.1
  image: ^3.0.1
  intent: ^1.4.0
#  extended_image: ^3.0.0
  video_thumbnail: ^0.2.5+1
  android_intent: ^2.0.0
  flutter_credit_card: ^0.1.4
  introduction_screen: ^2.0.0
  uuid: ^3.0.1
  geocoding:
  chewie: ^1.0.0
  video_player: ^2.0.2
  maps_toolkit: ^1.1.0+2
  focused_menu: ^1.0.5
  universal_platform: ^0.1.3
#  flutter_local_notifications:
  flutter_staggered_grid_view: ^0.3.4
  transparent_image: ^1.0.0
  image_size_getter: ^0.2.1
  get:
  crypto:
  hive: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

