name: monitorlibrary
description: Monitor Platform Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.3+1
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  permission_handler: ^5.0.1+1
  unicorndial: ^1.1.5
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.24
  sensors: ^0.4.2+6
  material_design_icons_flutter: ^4.0.5755
  flutter_google_places: ^0.2.6
  intl: ^0.16.1
  http: ^0.12.2
  google_maps_flutter: ^1.0.6
  google_maps_webservice: ^0.0.18
  autocomplete_textfield: ^1.7.3
  mongodb_mobile: ^0.0.7
  grouped_buttons: ^1.0.4
  path: ^1.7.0
  cached_network_image: ^2.3.3
  flutter_dotenv: ^2.1.0
  page_transition: ^1.1.7+2
  responsive_builder:
  google_fonts: ^1.1.1
  geolocator: ^6.1.8+1
  image: ^2.1.19
  intent: ^1.4.0
  extended_image: ^1.3.0
  video_thumbnail: ^0.2.4
  android_intent: ^0.3.7+7
  flutter_credit_card: ^0.1.3
  introduction_screen: ^1.0.9
  uuid: ^2.2.2
  geocoding: ^1.0.5
  chewie: ^0.12.0
  video_player: ^1.0.1
  maps_toolkit: ^1.1.0+2
  focused_menu: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

