name: monitorlibrary
description: Monitor Platform Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.4+1
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  permission_handler: ^5.0.1+1
  unicorndial: ^1.1.5
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.27
  sensors: ^0.4.2+6
  material_design_icons_flutter: ^4.0.5855
  flutter_google_places: ^0.2.6
  intl: ^0.16.1
  http: ^0.12.2
  google_maps_flutter: ^1.1.1
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^1.7.3
  mobmongo: ^0.0.8+1
  grouped_buttons: ^1.0.4
  path: ^1.7.0
  cached_network_image: ^2.5.0
  flutter_dotenv: ^3.1.0
  page_transition: ^1.1.7+6
  responsive_builder:
  google_fonts: ^1.1.2
  geolocator: ^6.1.14
  image: ^2.1.19
  intent: ^1.4.0
  extended_image: ^1.5.0
  video_thumbnail: ^0.2.5+1
  android_intent: ^0.3.7+7
  flutter_credit_card: ^0.1.4
  introduction_screen: ^1.0.9
  uuid: ^2.2.2
  geocoding: ^1.0.5
  chewie: ^0.12.2
  video_player: ^1.0.1
  maps_toolkit: ^1.1.0+2
  focused_menu: ^1.0.2
  universal_platform: ^0.1.3
  flutter_local_notifications: ^3.0.3
  flutter_staggered_grid_view: ^0.3.3
  transparent_image: ^1.0.0
  image_size_getter: ^0.2.1
  get:
  crypto:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

